language: python

python:
  - "2.7"

env:
  - DJANGO=1.10

services: mysql

addons:
  apt:
    packages:
      - mysql-server-5.5
      - libmysqlclient-dev
      - openssl
      - mysql-client-5.5
      - mysql-client-core-5.5

install: 
  - pip install -r requirements.txt

before_script:
  - "mysql -e 'CREATE DATABASE travisdb'"
  - "mysql -e 'SHOW DATABASES'"

script: "python manage.py test --settings=tark.tests.utils"
