from django.test import TestCase, RequestFactory, Client
from django.core.management import call_command
import json
import pprint

irak4_c2t = [{u'assembly': u'GRCh37.p13:GCA_000001405.14',
  u'transcripts': [{u'alt_seq': u'CTCGCCCCTTCGCGGCGCTTCCTAGTTCGGCTGGTTCTTCTGTCGCCGGCTTCAGCAGCCCGCGCCCGGGCAG',
                    u'exon': {u'assembly': u'GRCh37.p13:GCA_000001405.14',
                              u'exon_checksum': u'1247F1BE68A26DADEC48FE08DE552A76E8BE153C',
                              u'loc_checksum': u'141A3116667806D99CD61156D004EFCEABD8F79F',
                              u'loc_end': 44152819,
                              u'loc_region': u'12',
                              u'loc_start': 44152747,
                              u'loc_strand': 1,
                              u'seq_checksum': u'2A52107C4941074D5639704E6F452C140E874FF7',
                              u'sequence': u'CCCGCCCCTTCGCGGCGCTTCCTAGTTCGGCTGGTTCTTCTGTCGCCGGCTTCAGCAGCCCGCGCCCGGGCAG',
                              u'stable_id': u'ENSE00001267881',
                              u'stable_id_version': 8},
                    u'transcript': {u'assembly': u'GRCh37.p13:GCA_000001405.14',
                                    u'exon_set_checksum': u'5BA2D72B186B68FF49532D5E11E41185FC83D559',
                                    u'gene': u'ENSG00000198001.9',
                                    u'loc_checksum': u'2130589018243C2C2A173BB008492147EB1A26DC',
                                    u'loc_end': 44180778,
                                    u'loc_region': u'12',
                                    u'loc_start': 44152747,
                                    u'loc_strand': 1,
                                    u'seq_checksum': u'FD1A86BC11861B31B471E47728AAB7757D14DECA',
                                    u'sequence': u'CCCGCCCCTTCGCGGCGCTTCCTAGTTCGGCTGGTTCTTCTGTCGCCGGCTTCAGCAGCCCGCGCCCGGGCAGATGCTGTTCCCAAAACTGCTAATACACTACCTTCTAAAGAAGCTATAACAGTTCAGCAAAAACAGATGCCTTTCTGTGACAAAGACAGGACATTGATGACACCTGTGCAGAATCTTGAACAAAGCTATATGCCACCTGACTCCTCAAGTCCAGAAAATAAAAGTTTAGAAGTTAGTGATACACGTTTTCACAGTTTTTCATTTTATGAATTGAAGAATGTCACAAATAACTTTGATGAACGACCCATTTCTGTTGGTGGTAATAAAATGGGAGAGGGAGGATTTGGAGTTGTATATAAAGGCTACGTAAATAACACAACTGTGGCAGTGAAGAAGCTTGCAGCAATGGTTGACATTACTACTGAAGAACTGAAACAGCAGTTTGATCAAGAAATAAAAGTAATGGCAAAGTGTCAACATGAAAACTTAGTAGAACTACTTGGTTTCTCAAGTGATGGAGATGACCTCTGCTTAGTATATGTTTACATGCCTAATGGTTCATTGCTAGACAGACTCTCTTGCTTGGATGGTACTCCACCACTTTCTTGGCACATGAGATGCAAGATTGCTCAGGGTGCAGCTAATGGCATCAATTTTCTACATGAAAATCATCATATTCATAGAGATATTAAAAGTGCAAATATCTTACTGGATGAAGCTTTTACTGCTAAAATATCTGACTTTGGCCTTGCACGGGCTTCTGAGAAGTTTGCCCAGACAGTCATGACTAGCAGAATTGTGGGAACAACAGCTTATATGGCACCAGAAGCTTTGCGTGGAGAAATAACACCCAAATCTGATATTTACAGCTTTGGTGTGGTTTTACTAGAAATAATAACTGGACTTCCAGCTGTGGATGAACACCGTGAACCTCAGTTATTGCTAGATATTAAAGAAGAAATTGAAGATGAAGAAAAGACAATTGAAGATTATATTGATAAAAAGATGAATGATGCTGATTCCACTTCAGTTGAAGCTATGTACTCTGTTGCTAGTCAATGTCTGCATGAAAAGAAAAATAAGAGACCAGACATTAAGAAGGTTCAACAGCTGCTGCAAGAGATGACAGCTTCTTAAAACTTTATTGGAAAAGACTCTTGACTTTTTATATACACCTATCTCAACCATTTTTTTAACTGATTTTTTTCCTAAATATTCTTCTTTACCTTTAACAAGGCATAGGCTGTTGCAGGACAGTGGTTATTAAAGCATGGGTTGAACTTCCAAAATATAAAAATAGAGCCACCATATCAACACTTAGCCCTACCCATTAGTATCACCCCCAGTTCTTACAGTAATCCCTGAGAAATCTCCTTCAAGCATCACCAAACACAGTT',
                                    u'stable_id': u'ENST00000440781',
                                    u'stable_id_version': 2,
                                    u'transcript_checksum': u'C5983C3C2CCB347BD5013578FEA6B1F352779F3B'}}]},
 {u'assembly': u'GRCh38.p5:GCA_000001405.20',
  u'transcripts': [{u'alt_seq': u'CTCGCCCCTTCGCGGCGCTTCCTAGTTCGGCTGGTTCTTCTGTCGCCGGCTTCAGCAGCCCGCGCCCGGGCAG',
                    u'exon': {u'assembly': u'GRCh38.p5:GCA_000001405.20',
                              u'exon_checksum': u'5C897AAEE42E4853F85A60EABD32C58B0A7E5DC0',
                              u'loc_checksum': u'3B55D21413FBFA5E81A4CEEE22123A60D157E369',
                              u'loc_end': 43759016,
                              u'loc_region': u'12',
                              u'loc_start': 43758944,
                              u'loc_strand': 1,
                              u'seq_checksum': u'2A52107C4941074D5639704E6F452C140E874FF7',
                              u'sequence': u'CCCGCCCCTTCGCGGCGCTTCCTAGTTCGGCTGGTTCTTCTGTCGCCGGCTTCAGCAGCCCGCGCCCGGGCAG',
                              u'stable_id': u'ENSE00001267881',
                              u'stable_id_version': 8},
                    u'transcript': {u'assembly': u'GRCh38.p5:GCA_000001405.20',
                                    u'exon_set_checksum': u'DD49096A286B1804DE15083B745DE17065F9809B',
                                    u'gene': u'ENSG00000198001.13',
                                    u'loc_checksum': u'99A111EC484FFD4A4AE4B034FB7C2DECC8947DAE',
                                    u'loc_end': 43789543,
                                    u'loc_region': u'12',
                                    u'loc_start': 43758944,
                                    u'loc_strand': 1,
                                    u'seq_checksum': u'BF6F594F9D4A32A59C63FF60E3C9EC40C9750EE6',
                                    u'sequence': u'CCCGCCCCTTCGCGGCGCTTCCTAGTTCGGCTGGTTCTTCTGTCGCCGGCTTCAGCAGCCCGCGCCCGGGCAGGAATAGAAGATGAACAAACCCATAACACCATCAACATATGTGCGCTGCCTCAATGTTGGACTAATTAGGAAGCTGTCAGATTTTATTGATCCTCAAGAAGGATGGAAGAAGTTAGCTGTAGCTATTAAAAAACCATCTGGTGATGATAGATACAATCAGTTTCACATAAGATGCTGTTCCCAAAACTGCTAATACACTACCTTCTAAAGAAGCTATAACAGTTCAGCAAAAACAGATGCCTTTCTGTGACAAAGACAGGACATTGATGACACCTGTGCAGAATCTTGAACAAAGCTATATGCCACCTGACTCCTCAAGTCCAGAAAATAAAAGTTTAGAAGTTAGTGATACACGTTTTCACAGTTTTTCATTTTATGAATTGAAGAATGTCACAAATAACTTTGATGAACGACCCATTTCTGTTGGTGGTAATAAAATGGGAGAGGGAGGATTTGGAGTTGTATATAAAGGCTACGTAAATAACACAACTGTGGCAGTGAAGAAGCTTGCAGCAATGGTTGACATTACTACTGAAGAACTGAAACAGCAGTTTGATCAAGAAATAAAAGTAATGGCAAAGTGTCAACATGAAAACTTAGTAGAACTACTTGGTTTCTCAAGTGATGGAGATGACCTCTGCTTAGTATATGTTTACATGCCTAATGGTTCATTGCTAGACAGACTCTCTTGCTTGGATGGTACTCCACCACTTTCTTGGCACATGAGATGCAAGATTGCTCAGGGTGCAGCTAATGGCATCAATTTTCTACATGAAAATCATCATATTCATAGAGATATTAAAAGTGCAAATATCTTACTGGATGAAGCTTTTACTGCTAAAATATCTGACTTTGGCCTTGCACGGGCTTCTGAGAAGTTTGCCCAGACAGTCATGACTAGCAGAATTGTGGGAACAACAGCTTATATGGCACCAGAAGCTTTGCGTGGAGAAATAACACCCAAATCTGATATTTACAGCTTTGGTGTGGTTTTACTAGAAATAATAACTGGACTTCCAGCTGTGGATGAACACCGTGAACCTCAGTTATTGCTAGATATTAAAGAAGAAATTGAAGATGAAGAAAAGACAATTGAAGATTATATTGATAAAAAGATGAATGATGCTGATTCCACTTCAGTTGAAGCTATGTACTCTGTTGCTAGTCAATGTCTGCATGAAAAGAAAAATAAGAGACCAGACATTAAGAAGGTTCAACAGCTGCTGCAAGAGATGACAGCTTCTTAAAACTTTATTGGAAAAGACTCTTGACTTTTTATATACACCTATCTCAACCATTTTTTTAACTGATTTTTTTCCTAAATATTCTTCTTTACCTTTAACAAGGCATAGGCTGTTGCAGGACAGTGGTTATTAAAGCATGGGTTGAACTTCCAAAATATAAAAATAGAGCCACCATATCAACACTTAGCCCTACCCATTAGTATCACCCCCAGTTCTTACAGTAATCCCTGAGAAATCTCCTTCAAGCATCACCAAACACAGTTTGAAAATTACAGGGTTAGCAAAAAGAGCCTGGGCTGTATGTAGGGTGGAAACACTCTGATCTGAAGCCCAGCTGACTCCACTACTAATTTGCTGTAAAGCTTTGGACATACACTTAGCTGCTGTGAGCCACTAATAACATTGGGCTAATATCTGCTGTGCTTCTCTGACAGGTAGTCATGAAAATCAAATGATGCAAAATATATACAAGCACTTTGTAAATTGTAAAATGATACAAAATTTAAAGTTTATAGAGCCAGTTACAAAATCCTATTAGTCATATATTTATAGATTGTGTTCACAGCAATCATTTAACCACAAATAAAATATCCCTTGATGATACTGCCATAATGATATGTCCATTATTAGATTATGTTACATGACAAAGTTGAAGGAATTTGGCAGATGCAGTTAAGGTTCCTAAACAACTCACTTTGAGACTGTTGAAAGGGCCTGACCTAATCAAGTGAACCCTTGCAAGAAGAATTCTCCTTGTAAGCCTTGAAGAAGTATGTGAGAGGGCCACATTGGCTAAAACCTAAAGGTGGCCTCTAGGAGATGAGACCTACCTTCCAGTTGTCAGCAAGCAGGAAAAAAAAATTGGGACCTCAGTTGCAACCACAAGGAACTGAATTCTGCCAAAAATCTGAGTCAGCTTAGAAGAGTACTCCAAGCTTCAGATGATAACCACAGCCTGGGCTGACACCTGGATTTCAGCTTTGCATGATCCTCAGTATGAGAATCTATCTGTTCTGTGCTGGACTTCTAATATATAGAACTGTGAGATAATGGGTCACATTGGCTGGATGTGGTGGCTCATACCTGTAAATCCCAGCACTTTGGGAGGCCGAGGCAGGCAGATCACCTGAGGTCAAGAGTTCAAGACCGGCCTGGCCAACATGGTGAAACCCCGTCTCTACTAAAAATACAAAAATTAGACGAGCGTGGTGGTGGACACCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGACTAGCTGGAACCAGGGAGGTAGAGGTTGCAGTGAGCTGAGATCGTGCCACTGCACTCCAGCCTGGGTGACAGAGTGAGACTCCATCATAAATAAATAAATAAATAAATGGGTCACATTAAGCCTTTAAGTTTGTGGTAATTTATTATTCAGTAATAGAAAACAAATACAGATACTCTCCCATGATGTTTTTCCCATGATGATTTCCCATGATATTTACAGGTTTTGCCCACATTTGAGGGGTATGTGGAAATTATACAGAGCATGTACAGCGGGAGGCTTATAGTGTACGTACTGAAATGTGGGGTTGGAGCCCCAACACAGAGACCCCAGCAGGACACTGCCTAGTAGAGCTATGGGAAGGGTGCTGCCACCCTCCAGACTTGAGAATTGTAGAGCCACCAGCAGCTTGCACTCTGAGCTTGGAAAAGCCACAGGCACTCAACTTCAACCATGAGGGAAGCCACGCACCCTGCAAAGCCACAGGAGTGGAGCTGCCCACGGCCTCGAGGGCCCACCCCTTGCACCAGTGTGCCAGGATGTGGGACATGGAATCAAGGAATATGTTAGGGCTTTTTTTTTTTTTTTTTTGAGACGGAGTCTTGCTCTGTTGCCCAGGCTGGAGTGCAGTGGCACGATCTCGGCTCACTGCAAGCTCTGCCTCCCAGGTTCACGCCATTCCCCTGCCTCAGCCTCCCCAGTAGCTGGGACTACAGGTGCCCGCCACCATGCCCAGCTAATTTTTTTTGTATTTTTAGTAGAGATGGGGTTTCACTGTGTTAGCCAGGATGGTCTTGATCTCCTGACCTCGTGATCACCCGCCTCGGCCTCCCAAAGTGCCAGTATTTAAAGTTTAATGTCTTCCCAGCTGGGTTTCAGACTTGCCAGGATCCTGTTGCCCCTTTCTTTAGCCAATTTCTCCCTTTTGGGACAAGAATGTTTTACTTATTGCCTGTACCACCAACTGTATCTTGGAAATAAATAACTTATATTTTATTTCAGAGGCTCATAGGCGGCAGGAACTTACCTTGAGTCTCAAATGAGACTTAGGACTTTTGAGTGATGCTAGAATGAGTTAAGACTTTGGGAAGGGATGATTATATTTTGCAATGTGAGAAAGACATTAGATTTGGGGGGCTGGGGGTAGAATGACATTGTTTAGATGTTTGTCTCCTTCAAATTTCATGTTTAAATGTAATCCCCAGTGTTGGGGGTGGAGGTGGGGCCTGATGGGAAGTGTTTGGGTCATGGTGGATGATCCCTCATGAATGGCTTAGAGCCACTGGTGATGAGTGAGTTCTCACTCAGTTCGTGTGAGATCTGGTGGCTTAAAAGAGTCTGCTCCCCCTTTGCCTTCCATTGTGATTGTAACCTTCCTGGGGCCTTCATCAAAGGCCAGGCAAATATTGGTGCCGTGCTAGTATGGCCTGCAGAACCGTAAGCCAAAACAAACCTTTTTTCTTTATAAATTACCCAGCCTCAGTTATTCCTTTATAGTGATGCAAAACGGGCTAACTATATAAATTTGTAATTTTTAAGTTATAGATTGTTTTTATTAAACACTTATGAATACTGTT',
                                    u'stable_id': u'ENST00000431837',
                                    u'stable_id_version': 5,
                                    u'transcript_checksum': u'FDD44D3A5212077CE1E4C571DDFA98278CE8CBFD'}}]}]


class HGVSTestCase(TestCase):
    test_fixtures = ['session.json', 'genome.json', 'assembly.json', 'sequences.json', 'features.json', 'gene_names.json']
    
    def setUp(self):
        for fixture in self.test_fixtures:
            full_fixture = 'tark/tests/test-data/' + fixture
            print "Loading fixture {}".format(full_fixture)
            call_command('loaddata', full_fixture, verbosity=1)

        self.factory = RequestFactory()

    def testHGVSGene(self):
        print "Running HGVS g test"

        c = Client()

        response = c.get('/tark/lookup/hgvs/human/IRAK4:g.2C>T/')
        content = json.loads(''.join(response.streaming_content))
        self.assertEqual(irak4_c2t, content, "HGVS IRAK4:g.2C>T doesn't match content returned from the server")