swagger: '2.0'
info:
  version: 1.0.0
  title: Transcript Archive (TArK)
  description: |
    REST API for EBI-EMBL Transcript Archive
host: 'localhost:8000'
basePath: /tark/
schemes:
  - http
  - https
produces:
  - application/json
consumes:
  - application/json
parameters:
  identifier:
    name: id
    in: query
    description: 'Feature identifier, Ensembl stable id or Refseq accession'
    type: string
    required: true
  release-path:
    name: release
    in: path
    description: An Ensembl release tag
    type: string
    required: true
  tag-path:
    name: tag
    in: path
    description: An TArK tag
    type: string
    required: true
  species-path:
    name: species
    in: path
    description: Ensembl species name or alias
    type: string
    default: human
    required: true
  assembly-path:
    name: assembly
    in: path
    description: 'Species assembly (GRCh37, GRCh38...)'
    type: string
    default: GRCh38
    required: true
  hgvs-path:
    name: hgvs
    in: path
    description: HGVS string
    type: string
    default: 'IRAK4:g.9159_9160delGA'
    required: true
  ids:
    name: id
    in: body
    description: 'Feature identifier, Ensembl stable id or Refseq accession'
    schema:
      required:
        - id
      properties:
        id:
          type: array
          items:
            type: number
    required: true
  location-body:
    name: locations
    in: body
    description: 'Genomic location (1:2000-3000, X:40000-50000:-1) and set (GRCh38, etc)'
    schema:
      required:
        - locations
      properties:
        locations:
          type: array
          items:
            type: string
        set:
          type: string
          default: GRCh38
  gene-name:
    name: name
    in: query
    description: Gene name to retrieve
    type: string
    default: IRAK4
    required: true
  gene-names:
    name: names
    in: body
    description: Gene name(s) to retrieve
    schema:
      required:
        - name
      properties:
        name:
          type: array
          items:
            type: string
    required: true
  expand:
    name: expand
    in: query
    description: 'Expand the feature to show child features, if they exist'
    type: boolean
    default: false
    required: false
  skip_sequence:
    name: skip_sequence
    in: query
    description: Skip returning the sequence in the feature objects
    type: boolean
    default: false
    required: false
  filter_pk:
    name: filter_pk
    in: query
    description: Skip returning the sequence in the feature objects
    default: true
    type: boolean
    required: false
  feature-query:
    name: feature-type
    in: query
    description: Type of feature
    type: string
    enum:
      - gene
      - transcript
      - exon
      - translation
    required: false
  assembly:
    name: assembly
    in: query
    description: 'Species assembly (GRCh37, GRCh38...)'
    type: string
    required: false
  location-string:
    name: location
    in: query
    description: 'Genomic region string (1:2000-3000, X:40000-50000:-1)'
    type: string
    default: 'X:10000-20000'
    required: true
  location-region:
    name: region
    in: query
    description: Location region
    type: string
    default: '12'
    required: true
  location-start:
    name: start
    in: query
    description: Location start coordinate
    type: number
    default: 43750000
    required: true
  location-end:
    name: end
    in: query
    description: Location end coordinate
    type: number
    default: 43790000
    required: true
  assembly1:
    name: assembly1
    in: query
    description: Assembly of the first set
    type: string
    default: GRCh38
    required: true
  assembly2:
    name: assembly2
    in: query
    description: Assembly of the second set
    type: string
    default: GRCh38
    required: true
  release1:
    name: release1
    in: path
    description: Release tag of the first group
    type: string
    default: '90'
    required: true
  release2:
    name: release2
    in: path
    description: Release tag of the second group
    type: string
    default: '89'
    required: true
paths:
  /genome/:
    get:
      produces:
        - application/json
      description: |
        List all available species in the database
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/genome'
  '/assembly/{species}/':
    parameters:
      - $ref: '#/parameters/species-path'
    get:
      produces:
        - application/json
      description: |
        Show all assemblies for a given species
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/assembly'
  /lookup/gene/:
    parameters:
      - $ref: '#/parameters/assembly'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
      - $ref: '#/parameters/filter_pk'
    get:
      parameters:
        - $ref: '#/parameters/identifier'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Gets `Sequence` objects for genes.
        Returns one or more gene objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/gene_obj'
    post:
      parameters:
        - $ref: '#/parameters/ids'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Gets `Sequence` objects for genes.
        Returns one or more gene objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/gene_obj'
  /lookup/transcript/:
    parameters:
      - $ref: '#/parameters/assembly'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
      - $ref: '#/parameters/filter_pk'
    get:
      parameters:
        - $ref: '#/parameters/identifier'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Gets `Sequence` objects for transcript.
        Returns one or more transcript objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/transcript_obj'
    post:
      parameters:
        - $ref: '#/parameters/ids'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Gets `Sequence` objects for transcript.
        Returns one or more sequence objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/transcript_obj'
  /lookup/exon/:
    parameters:
      - $ref: '#/parameters/assembly'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
      - $ref: '#/parameters/filter_pk'
    get:
      parameters:
        - $ref: '#/parameters/identifier'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Gets `Sequence` objects for exon.
        Returns one or more exon objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/exon_obj'
    post:
      parameters:
        - $ref: '#/parameters/ids'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Gets `Sequence` objects for exon.
        Returns one or more exon objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/exon_obj'
  /lookup/translation/:
    parameters:
      - $ref: '#/parameters/assembly'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
      - $ref: '#/parameters/filter_pk'
    get:
      parameters:
        - $ref: '#/parameters/identifier'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Gets `Sequence` objects for translation.
        Returns one or more translation objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/translation_obj'
    post:
      parameters:
        - $ref: '#/parameters/ids'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Gets `Sequence` objects for translation.
        Returns one or more translation objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/translation_obj'
  /lookup/name/gene/:
    parameters:
      - $ref: '#/parameters/assembly'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
    get:
      parameters:
        - $ref: '#/parameters/gene-name'
      produces:
        - application/json
      description: |
        Lookup a gene name and return the gene objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/gene_obj'
    post:
      parameters:
        - $ref: '#/parameters/gene-names'
      produces:
        - application/json
      description: |
        Lookup a gene(s) and return the gene objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/gene_obj'
  /lookup/name/transcript/:
    parameters:
      - $ref: '#/parameters/assembly'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
    get:
      parameters:
        - $ref: '#/parameters/gene-name'
      produces:
        - application/json
      description: |
        Lookup a gene name and return the transcript objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/transcript_obj'
    post:
      parameters:
        - $ref: '#/parameters/gene-names'
      produces:
        - application/json
      description: |
        Lookup a gene(s) and return the transcript objects
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/transcript_obj'
  '/location/{species}/gene/':
    parameters:
      - $ref: '#/parameters/species-path'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
    get:
      parameters:
        - $ref: '#/parameters/assembly'
        - $ref: '#/parameters/location-region'
        - $ref: '#/parameters/location-start'
        - $ref: '#/parameters/location-end'
      produces:
        - application/json
      description: |
        Find all gene objects within a region
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/gene_obj'
    post:
      parameters:
        - $ref: '#/parameters/location-body'
      produces:
        - application/json
      description: |
        Find all gene objects within a region
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/gene_obj'
  '/location/{species}/transcript/':
    parameters:
      - $ref: '#/parameters/species-path'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
    get:
      parameters:
        - $ref: '#/parameters/assembly'
        - $ref: '#/parameters/location-region'
        - $ref: '#/parameters/location-start'
        - $ref: '#/parameters/location-end'
      produces:
        - application/json
      description: |
        Find all transcript objects within a region
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/transcript_obj'
    post:
      parameters:
        - $ref: '#/parameters/location-body'
      produces:
        - application/json
      description: |
        Find all transcript objects within a region
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/transcript_obj'
  '/location/{species}/exon/':
    parameters:
      - $ref: '#/parameters/species-path'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
    get:
      parameters:
        - $ref: '#/parameters/assembly'
        - $ref: '#/parameters/location-region'
        - $ref: '#/parameters/location-start'
        - $ref: '#/parameters/location-end'
      produces:
        - application/json
      description: |
        Find all exon objects within a region
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/exon_obj'
    post:
      parameters:
        - $ref: '#/parameters/location-body'
      produces:
        - application/json
      description: |
        Find all exon objects within a region
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/exon_obj'
  '/location/{species}/translation/':
    parameters:
      - $ref: '#/parameters/species-path'
      - $ref: '#/parameters/expand'
      - $ref: '#/parameters/skip_sequence'
    get:
      parameters:
        - $ref: '#/parameters/assembly'
        - $ref: '#/parameters/location-region'
        - $ref: '#/parameters/location-start'
        - $ref: '#/parameters/location-end'
      produces:
        - application/json
      description: |
        Find all translation objects within a region
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/translation_obj'
    post:
      parameters:
        - $ref: '#/parameters/location-body'
      produces:
        - application/json
      description: |
        Find all translation objects within a region
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/translation_obj'
  '/sequence/region/{assembly}/':
    parameters:
      - $ref: '#/parameters/assembly-path'
    get:
      parameters:
        - $ref: '#/parameters/location-string'
      produces:
        - application/json
        - text/x-fasta
        - text/plain
      description: |
        Fetch a sequence region, if available
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/sequence'
    post:
      parameters:
        - $ref: '#/parameters/location-body'
      produces:
        - application/json
        - text/x-fasta
      description: |
        Fetch one or more sequence regions, if available
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/sequence'
  '/diff/{species}/{release1}/{release2}/':
    parameters:
      - $ref: '#/parameters/species-path'
      - $ref: '#/parameters/release1'
      - $ref: '#/parameters/assembly1'
      - $ref: '#/parameters/release2'
      - $ref: '#/parameters/assembly2'
    get:
      produces:
        - application/json
      description: |
        Find the differences between two release sets.
        For each set, a release and assembly are required.
        WARNING: Produces a very large resultset.
      responses:
        '200':
          description: Success
  '/lookup/hgvs/{species}/{hgvs}/':
    parameters:
      - $ref: '#/parameters/species-path'
      - $ref: '#/parameters/hgvs-path'
      - $ref: '#/parameters/assembly'
    get:
      produces:
        - application/json
      description: |
        Retrieve all transcripts matching the HGVS string
        Currently only handles g. level strings.
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/transcript_obj'
definitions:
  gene_obj:
    type: object
    properties:
      assembly:
        type: string
        description: Assembly version
      stable_id:
        type: string
        description: Feature stable id
      stable_id_version:
        type: string
      loc_region:
        type: string
      loc_strand:
        type: string
      loc_start:
        type: string
      loc_end:
        type: string
      gene_checksum:
        type: string
      seq_checksum:
        type: string
      sequence:
        type: string
      transcript:
        type: array
        items:
          $ref: '#/definitions/transcript_obj'
  transcript_obj:
    type: object
    properties:
      assembly:
        type: string
      stable_id:
        type: string
      stable_id_version:
        type: string
      loc_region:
        type: string
      loc_strand:
        type: string
      loc_start:
        type: string
      loc_end:
        type: string
      loc_checksum:
        type: string
      transcript_checksum:
        type: string
      exon_set_checksum:
        type: string
      gene:
        type: string
      seq_checksum:
        type: string
      sequence:
        type: string
      exon:
        type: array
        items:
          $ref: '#/definitions/exon_obj'
      translation:
        type: array
        items:
          $ref: '#/definitions/translation_obj'
  exon_obj:
    type: object
    properties:
      assembly:
        type: string
      stable_id:
        type: string
      stable_id_version:
        type: string
      loc_region:
        type: string
      loc_strand:
        type: string
      loc_start:
        type: string
      loc_end:
        type: string
      loc_checksum:
        type: string
      exon_checksum:
        type: string
      seq_checksum:
        type: string
      sequence:
        type: string
  translation_obj:
    type: object
    properties:
      assembly:
        type: string
      stable_id:
        type: string
      stable_id_version:
        type: string
      loc_region:
        type: string
      loc_strand:
        type: string
      loc_start:
        type: string
      loc_end:
        type: string
      loc_checksum:
        type: string
      translation_checksum:
        type: string
      transcript:
        type: string
      seq_checksum:
        type: string
      sequence:
        type: string
  checksum:
    type: object
    properties:
      checksum:
        type: string
  location:
    type: object
    properties:
      assembly:
        type: string
      region:
        type: string
      start:
        type: number
      end:
        type: number
  sequence:
    type: object
    properties:
      location:
        type: string
      sequence:
        type: string
  assembly:
    type: object
    properties:
      species:
        type: string
      name:
        type: string
      accession:
        type: string
      version:
        type: number
  genome:
    type: object
    properties:
      name:
        type: string
      taxonomy:
        type: number
